# YAML file to trigger the fetching of issue comments using the py file below

name: Fetch Issue Comments

on:
  workflow_dispatch: # manual trigger for the GitHub UI
    inputs:
      owner:
        description: "Repository owner (organization or user) "
        required: true
        default: "hackforla"
      repo:
        description: "Repository name"
        required: true
        default: "website"
      users:
        description: "Comma-separated list of GitHub usernames to keep"
        required: true
        default: "JasonUranta,JackRichman,mgodoy2023,Zak234,anonymousanemone"


  issue_comment:
    types: [created]


jobs:
  fetch-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests
        
      - name: Run comment fetcher
        env:
          # "GH_TOKEN" is the personal access token needed to authenticate from GitHub
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          INPUT_OWNER: ${{ github.event.inputs.owner || 'hackforla' }}
          INPUT_REPO:  ${{ github.event.inputs.repo  || 'website' }}
          INPUT_USERS: ${{ github.event.inputs.users || 'JasonUranta,JackRichman,mgodoy2023,Zak234,anonymousanemone' }}
        run: python scripts/fetch-issue-comments.py
