name: POC Repo Contributions Fetcher

on:
  workflow_dispatch:

jobs:
  fetch_issues_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: mixin

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: pip install requests

      - name: Check for GH_TOKEN (PAT)
        run: |
          if [ -z "${{ secrets.PAT }}" ]; then
            echo "::error::GH_TOKEN (PAT) is not set"
            exit 1
          fi

      - name: Run Repo Fetcher Script
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          python issue_contributor_fetcher/poc_repo_fetcher/poc_repo_fetcher.py

      - name: Upload CSV Results
        uses: actions/upload-artifact@v4
        with:
          name: poc-results
          path: issue_contributor_fetcher/poc_repo_fetcher/poc_repo_fetcher_results.csv
